#
#    Copyright 2010-2018 the original author or authors.
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
#

---
apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    name: development
    env: dev
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: jpets
  namespace: dev
  annotations:
    kubernetes.io/change-cause: upgrading version
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jpets
  template:
    metadata:
      labels:
        app: jpets
        env: dev
    spec:
      containers:
      - name: jpets
        image: localhost:8083/jpets:18
        ports:
        - containerPort: 8080
      imagePullSecrets: 
      - name: nexussecret 
---
kind: Service
apiVersion: v1
metadata:
  name: jpets-service
  namespace: dev
  labels:
    app: jpets-dev
spec:
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30008
  selector:
    app: jpets
    env: dev
  type: NodePort 

